In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/home/kifaru/projects/data-viz/Data/sacco.csv")

In [3]:
df.head()

,member_id,full_name,age,county,employment_sector,employer_name,monthly_contribution,date_joined,phone_number,gender,member_status,remarks
0,SACCO-0001,Kamau Mutua,28yrs,Marsabit,Agriculture,East African Breweries,"KES 23,795",Feb-2015,2.547678e+11,Female,ACTIVE,NaN
1,SACCO-0002,Salome Nyambura,22 years,Uasin Gishu,Transport,Absa Kenya,NaN,2017-04,7.451770e+08,F,Inactive,NaN
2,SACCO-0003,OWINO Kiptoo,29,Siaya,Agriculture,Bamburi Cement,NaN,06/2024,7.945660e+08,Female,inactive,NaN
3,SACCO-0004,Odhiambo sigei,62,Uasin Gishu,Trade,Cooperative Bank,76575,2019-12,7.869778e+08,Female,active,NaN
4,SACCO-0005,Mercy Lagat,57,Narok,ICT,World Vision Kenya,4272.0,2018-01,7.538434e+08,M,INACTIVE,NaN

In [4]:
#df.to_excel("/home/kifaru/Desktop/sacco.xlsx")

In [5]:
df.describe()

       phone_number
count  8.430000e+02
mean   1.257913e+11
std    1.270606e+11
min    7.003443e+08
25%    7.476000e+08
50%    7.983646e+08
75%    2.547481e+11
max    2.547997e+11

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   member_id             1000 non-null   str
 1   full_name             1000 non-null   str
 2   age                   950 non-null    str
 3   county                1000 non-null   str
 4   employment_sector     1000 non-null   str
 5   employer_name         895 non-null    str
 6   monthly_contribution  800 non-null    str
 7   date_joined           1000 non-null   str
 8   phone_number          843 non-null    float64
 9   gender                1000 non-null   str
 10  member_status         1000 non-null   str
 11  remarks               28 non-null     str
dtypes: float64(1), str(11)
memory usage: 93.9 KB

In [7]:
df_clean = df.replace(" " ,np.nan)

In [8]:
df_clean.head()

,member_id,full_name,age,county,employment_sector,employer_name,monthly_contribution,date_joined,phone_number,gender,member_status,remarks
0,SACCO-0001,Kamau Mutua,28yrs,Marsabit,Agriculture,East African Breweries,"KES 23,795",Feb-2015,2.547678e+11,Female,ACTIVE,NaN
1,SACCO-0002,Salome Nyambura,22 years,Uasin Gishu,Transport,Absa Kenya,NaN,2017-04,7.451770e+08,F,Inactive,NaN
2,SACCO-0003,OWINO Kiptoo,29,Siaya,Agriculture,Bamburi Cement,NaN,06/2024,7.945660e+08,Female,inactive,NaN
3,SACCO-0004,Odhiambo sigei,62,Uasin Gishu,Trade,Cooperative Bank,76575,2019-12,7.869778e+08,Female,active,NaN
4,SACCO-0005,Mercy Lagat,57,Narok,ICT,World Vision Kenya,4272.0,2018-01,7.538434e+08,M,INACTIVE,NaN

In [9]:
#finding the sum of the missing values
df_clean.isnull().sum()

member_id                 0
full_name                 0
age                      50
county                    0
employment_sector         0
employer_name           105
monthly_contribution    200
date_joined               0
phone_number            157
gender                    0
member_status             0
remarks                 972
dtype: int64

In [10]:
missing_data = df[["age","employer_name","monthly_contribution","phone_number","remarks"]].isnull().sum()
print(missing_data)

age                      50
employer_name           105
monthly_contribution    200
phone_number            157
remarks                 972
dtype: int64

In [11]:
original_data = len(df)
print(original_data)

1000

In [12]:
#finding the percentage of each column missing
percentage_missing = missing_data / original_data *100
print(percentage_missing.round(2).astype(str) + "%")

age                      5.0%
employer_name           10.5%
monthly_contribution    20.0%
phone_number            15.7%
remarks                 97.2%
dtype: str

In [13]:
df["member_id"].duplicated().sum()

np.int64(30)

In [26]:
#Preprocessing
df[df["member_id"].duplicated(keep=False)]

,member_id,full_name,age,county,employment_sector,employer_name,monthly_contribution,date_joined,phone_number,gender,member_status,remarks
8,SACCO-0070,Beatrice Korir,34,Uasin Gishu,Finance,World Vision Kenya,NaN,Oct-2015,7.026141e+08,F,INACTIVE,NaN
42,SACCO-0043,Samuel Njoroge,55yrs,Meru,ICT,Nairobi City County,NaN,Mar-2020,2.547950e+11,F,INACTIVE,NaN
69,SACCO-0070,KAMAU Wekesa,37yrs,Mombasa,Manufacturing,Kisumu County Govt,5298,Sep-2021,2.547085e+11,m,active,NaN
111,SACCO-0112,Kiptoo Cheruiyot,42,Uasin Gishu,Public Service,Total Kenya,NaN,Aug-2019,2.547528e+11,FEMALE,Active,NaN
128,SACCO-0129,Adhiambo Mwangi,27yrs,Isiolo,Transport,Cooperative Bank,49538,Feb-2024,NaN,M,active,NaN
166,SACCO-0167,Samuel Odongo,61yrs,Uasin Gishu,Finance,Kenya Railways,NaN,01/2018,7.714415e+08,Male,Inactive,NaN
172,SACCO-0341,Omondi Kariuki,59,Lamu,Public Service,Kenya Power,6004,2020-02,2.547567e+11,Male,Active,NaN
174,SACCO-0451,Salome Kamau,27,Kisii,ICT,Safaricom PLC,9306.0,2021-06,2.547422e+11,F,active,NaN
180,SACCO-0317,Chebet Mutua,29 years,Mombasa,Trade,Teachers Service Commission,"KES 6,030",Feb-2023,2.547774e+11,Male,active,NaN
186,SACCO-0240,Zawadi Waithera,28yrs,Tharaka-Nithi,ICT,Standard Chartered,NaN,01/2024,7.175434e+08,F,Inactive,NaN
203,SACCO-0212,Paul Bett,43,Bungoma,Public Service,Kenya Red Cross,"KES 12,737",05/2023,7.399164e+08,M,active,NaN
211,SACCO-0212,CATHERINE Nyambura,39,Mombasa,Trade,NHIF,NaN,2019-05,2.547934e+11,FEMALE,Active,NaN
220,SACCO-0444,Rose Kipchoge,38 years,Turkana,ICT,Kenya Pipeline Company,8202,Nov-2020,7.476853e+08,f,Inactive,NaN
239,SACCO-0240,Juma Ogutu,43,Migori,Agriculture,Kenya Pipeline Company,1159.0,2024-02,2.547605e+11,Female,active,NaN
271,SACCO-0400,Njeri Korir,38,Mandera,Transport,Teachers Service Commission,13423,02/2023,NaN,m,Inactive,NaN
278,SACCO-0384,John Gathoni,58,Busia,Public Service,East African Breweries,"KES 70,151",2018-06,2.547616e+11,MALE,inactive,NaN
303,SACCO-0304,Fatuma Cheruiyot,22 years,Garissa,Public Service,AMREF,1456,2015-10,7.832415e+08,m,ACTIVE,NaN
316,SACCO-0317,Florence Muthoni,42,Kitui,Agriculture,World Vision Kenya,3604,2020-10,2.547594e+11,Male,INACTIVE,NaN
340,SACCO-0341,Chebet njoroge,56,Kwale,ICT,NHIF,"KES 5,048",Sep-2015,2.547973e+11,Male,Active,NaN
341,SACCO-0944,Abdi Kiptoo,26,Nyandarua,ICT,Kenya Power,15996,11/2021,2.547223e+11,F,active,NaN
344,SACCO-0425,Moses Ochieng,55,Kajiado,Agriculture,PWC Kenya,5.1K,06/2016,7.061928e+08,m,ACTIVE,NaN
383,SACCO-0384,Beatrice Rotich,30,West Pokot,Agriculture,Kisumu County Govt,20913,08/2022,7.461140e+08,F,Active,NaN
399,SACCO-0400,John Ochieng,31 years,Vihiga,Trade,Standard Chartered,"KES 13,801",Jun-2019,2.547598e+11,M,ACTIVE,NaN
424,SACCO-0425,James Kiptoo,44 years,Kitui,ICT,Mombasa County Govt,NaN,07/2019,7.420575e+08,F,active,NaN
435,SACCO-0551,Wanjiku Lagat,58,Uasin Gishu,Manufacturing,Total Kenya,17907.0,10/2017,2.547429e+11,f,Active,NaN
442,SACCO-0304,Rotich gathoni,30,Nyandarua,Transport,Cooperative Bank,3.2K,05/2019,2.547354e+11,F,Active,NaN
443,SACCO-0444,Daniel Njenga,64yrs,Busia,Agriculture,Nairobi City County,23328,Mar-2018,NaN,Male,Active,NaN
446,SACCO-0447,Agnes Kimani,28,Kakamega,Agriculture,NaN,"KES 11,051",08/2022,2.547361e+11,M,INACTIVE,NaN
448,SACCO-0449,JUMA Mutuku,46 years,Laikipia,Transport,NaN,71.4K,Feb-2017,2.547580e+11,MALE,INACTIVE,NaN
450,SACCO-0451,Abdi Waithera,31,Isiolo,Transport,Deloitte Kenya,"KES 1,491",08/2019,7.641039e+08,FEMALE,ACTIVE,NaN
478,SACCO-0479,Achieng Odongo,54,Nyeri,Transport,Kenya Pipeline Company,"KES 24,896",2015-05,2.547329e+11,f,active,Verified
481,SACCO-0112,Wafula Ochieng,59,Garissa,ICT,Total Kenya,"KES 62,805",May-2016,2.547624e+11,M,Active,NaN
482,SACCO-0733,Kamau Gathoni,NaN,Turkana,Transport,Teachers Service Commission,13237,07/2024,2.547853e+11,f,Active,NaN
523,SACCO-0447,Florence Mutuku,64,Uasin Gishu,Agriculture,Absa Kenya,"KES 7,165",06/2020,2.547254e+11,MALE,Inactive,NaN
529,SACCO-0632,Florence Nyambura,36yrs,Siaya,Finance,Kenya Airways,48289,2015-02,NaN,M,INACTIVE,NaN
538,SACCO-0539,Omondi Mutuku,48yrs,Nyamira,Public Service,KEBS,NaN,Dec-2017,7.652931e+08,FEMALE,active,NaN
550,SACCO-0551,Catherine Ochieng,29,Mandera,Finance,NaN,31833.0,Aug-2018,7.505610e+08,f,Active,NaN
572,SACCO-0573,Omondi Muthoni,54,Migori,Agriculture,Kenya Pipeline Company,"KES 3,569",Nov-2017,7.631761e+08,F,Inactive,VIP member
613,SACCO-0695,Zawadi Kiptoo,25,Mombasa,ICT,PWC Kenya,"KES 67,144",Nov-2019,NaN,F,Active,NaN
631,SACCO-0632,Faith Muthoni,42yrs,Baringo,Public Service,Absa Kenya,3282,2020-06,2.547086e+11,MALE,INACTIVE,NaN
642,SACCO-0815,Ndegwa Njenga,49,Kajiado,ICT,East African Breweries,NaN,2017-08,7.999957e+08,M,active,NaN
694,SACCO-0695,John Sigei,49,Homa Bay,Transport,Bamburi Cement,5349,Feb-2019,2.547452e+11,Female,INACTIVE,NaN
700,SACCO-0539,Wafula Waithera,27,Nyandarua,Transport,PWC Kenya,21116,2020-02,2.547299e+11,F,active,NaN
725,SACCO-0167,Ndegwa Kariuki,45,Garissa,Agriculture,Nation Media Group,5768,11/2019,NaN,m,Active,NaN
732,SACCO-0733,Owino Wanjiku,44yrs,Nandi,ICT,Deloitte Kenya,"KES 68,843",2017-01,7.785473e+08,Male,Active,NaN
733,SACCO-0449,Halima Otieno,35,Garissa,Finance,NHIF,19704.0,02/2019,7.282826e+08,Male,Active,NaN
743,SACCO-0744,Chebet Odongo,22,Makueni,Public Service,Absa Kenya,3830.0,Jul-2019,7.851098e+08,f,INACTIVE,NaN
746,SACCO-0747,HALIMA Muthoni,62,Nyeri,Trade,AMREF,7614,Apr-2021,7.718045e+08,m,active,NaN
783,SACCO-0479,Catherine Mutua,23,Laikipia,Agriculture,Nation Media Group,7.8K,Jan-2015,7.573311e+08,f,active,NaN
795,SACCO-0043,Otieno Mutua,NaN,Kilifi,Agriculture,Kenya Railways,21772.0,Mar-2018,2.547016e+11,Male,Inactive,NaN
814,SACCO-0815,KARANJA Wekesa,23,Taita-Taveta,ICT,Kenya Breweries,"KES 23,444",Oct-2023,2.547250e+11,Female,active,NaN
818,SACCO-0129,Moses Gathoni,23 years,Tana River,Public Service,NaN,NaN,Jul-2017,7.606814e+08,m,Inactive,NaN
851,SACCO-0852,Joseph Kariuki,46,Taita-Taveta,Public Service,Standard Chartered,4481,Dec-2019,2.547492e+11,f,inactive,NaN
863,SACCO-0573,SALOME Njoroge,32,Kajiado,Transport,Nation Media Group,"KES 45,645",Oct-2016,7.378356e+08,F,ACTIVE,NaN
870,SACCO-0747,Rose Kariuki,47,Elgeyo-Marakwet,ICT,World Vision Kenya,18320,06/2019,7.763068e+08,Male,ACTIVE,NaN
895,SACCO-0744,Abdi Sigei,36 years,Wajir,Agriculture,Safaricom PLC,NaN,2017-12,2.547812e+11,F,Inactive,NaN
914,SACCO-0852,Zawadi Wekesa,65,Homa Bay,Manufacturing,Nairobi City County,18160,May-2021,NaN,F,inactive,NaN
943,SACCO-0944,Juma Bett,61,Nyamira,ICT,Equity Bank,NaN,Sep-2024,7.612619e+08,F,Inactive,NaN
956,SACCO-0979,NJERI Nyambura,57 years,Machakos,ICT,Kenya Red Cross,"KES 13,870",12/2024,2.547741e+11,M,Inactive,NaN
978,SACCO-0979,Wafula Onyango,59 years,Kisii,Agriculture,Total Kenya,6668,Mar-2018,2.547068e+11,Female,inactive,NaN

In [27]:
df["age"].head()

0       28yrs
1    22 years
2          29
3          62
4          57
Name: age, dtype: str

In [28]:
df["age"].unique()

<StringArray>
[   '28yrs', '22 years',       '29',       '62',       '57',       '63',
 '39 years',       '34',       '27',       '41',
 ...
    '39yrs', '23 years',    '38yrs', '59 years', '62 years', '53 years',
 '36 years', '50 years',    '58yrs', '57 years']
Length: 128, dtype: str

In [31]:
#Cleaning age column
df["age"] = (df["age"].astype("string")
    .str.replace("yrs","",regex=False)
    .str.replace("years","",regex=False))

In [32]:
df["age"] = pd.to_numeric(df["age"],errors="coerce")

In [33]:
df["age"].head()

0    28
1    22
2    29
3    62
4    57
Name: age, dtype: Int64

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   member_id             1000 non-null   str
 1   full_name             1000 non-null   str
 2   age                   950 non-null    Int64
 3   county                1000 non-null   str
 4   employment_sector     1000 non-null   str
 5   employer_name         895 non-null    str
 6   monthly_contribution  800 non-null    str
 7   date_joined           1000 non-null   str
 8   phone_number          843 non-null    float64
 9   gender                1000 non-null   str
 10  member_status         1000 non-null   str
 11  remarks               28 non-null     str
dtypes: Int64(1), float64(1), str(10)
memory usage: 94.9 KB

In [37]:
#minimum age
minimum_age= df["age"].min()
print(minimum_age)

22

In [39]:
#maximum age
maximum_age = df["age"].max()
print(maximum_age)

65

In [44]:
#mean
mean = df["age"].mean()
print(mean)

43.55789473684211

In [46]:
#median
median = df["age"].median()
print(median)

43.0

In [49]:
df.to_excel("/home/kifaru/Desktop/sacco.xlsx")