In [1]:
import pandas as pd
import numpy as np

In [7]:
Data = {
    "Cumstomer" : ["c001","c002","c003","c004","c005","c006","c007","c008"] ,
    "Distance_km" : [2,15,7,25,4,12,30,6] ,
    "Delivery_Time_min" : [25,70,40,110,30,65,140,35] ,
    "Orders_per_month" : [12,4,8,2,15,6,1,10] ,
    "Money_spent_KES" : [8400,5200,11000,3500,14500,7600,2200,12500] 
}

In [8]:
df = pd.DataFrame(Data)

In [9]:
df.describe()

       Distance_km  Delivery_Time_min  Orders_per_month  Money_spent_KES
count     8.000000           8.000000          8.000000         8.000000
mean     12.625000          64.375000          7.250000      8112.500000
std      10.169106          41.441654          4.920801      4366.246345
min       2.000000          25.000000          1.000000      2200.000000
25%       5.500000          33.750000          3.500000      4775.000000
50%       9.500000          52.500000          7.000000      8000.000000
75%      17.500000          80.000000         10.500000     11375.000000
max      30.000000         140.000000         15.000000     14500.000000

In [10]:
df.head()

  Cumstomer  Distance_km  Delivery_Time_min  Orders_per_month  Money_spent_KES
0      c001            2                 25                12             8400
1      c002           15                 70                 4             5200
2      c003            7                 40                 8            11000
3      c004           25                110                 2             3500
4      c005            4                 30                15            14500

In [11]:
#Money_spent_KES has the highest value
#Orders_per_month has the smallest 
#Yes the difference could affect K-Means

In [46]:
Distance_normalized =( df["Distance_km"] - df["Distance_km"].min() ) / (df["Distance_km"].max() -df["Distance_km"].min())

print(Distance_normalized)

0    0.000000
1    0.464286
2    0.178571
3    0.821429
4    0.071429
5    0.357143
6    1.000000
7    0.142857
Name: Distance_km, dtype: float64

In [47]:
Time_normalized = (df["Delivery_Time_min"] - df["Delivery_Time_min"].min()) / (df["Delivery_Time_min"].max() -df["Delivery_Time_min"].min())
print(Time_normalized)

0    0.000000
1    0.391304
2    0.130435
3    0.739130
4    0.043478
5    0.347826
6    1.000000
7    0.086957
Name: Delivery_Time_min, dtype: float64

In [48]:
Orders_normalized = (df["Orders_per_month"] - df["Orders_per_month"].min()) / (df["Orders_per_month"].max() -df["Orders_per_month"].min())
print(Orders_normalized)

0    0.785714
1    0.214286
2    0.500000
3    0.071429
4    1.000000
5    0.357143
6    0.000000
7    0.642857
Name: Orders_per_month, dtype: float64

In [49]:
Money_normalized = (df["Money_spent_KES"] - df["Money_spent_KES"].min()) / (df["Money_spent_KES"].max() -df["Money_spent_KES"].min())
print(Money_normalized)

0    0.504065
1    0.243902
2    0.715447
3    0.105691
4    1.000000
5    0.439024
6    0.000000
7    0.837398
Name: Money_spent_KES, dtype: float64

In [43]:
#Euclidean distance before  normalization c001 and c005
6100
#Euclidean distance after normalization c001 and c005
800